config/routes.rb
Rails.application.routes.draw do

  root 'songs#index'
  resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  def self.search(title, artist, album)
    if title || artist || album
      where('title LIKE ? AND artist LIKE ? AND album LIKE ?', "%#{title}%", "%#{artist}%", "%#{album}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @songs = Song.search(params[:title], params[:artist], params[:album]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  private

  def sort_column
    Song.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TuneCore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <center>
    <%= yield %>
  </center>
</body>
</html>

app/views/songs/_songs.html.erb
<table class='table table-striped table-condensed'>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Album</th>
  </tr>
  <% @songs.each do |song| %>
    <tr>
      <td class="col-md-2"><%= song.title %></td>
      <td class="col-md-2"><%= song.artist %></td>
      <td class="col-md-2"><%= song.album %></td>
    </tr>
  <% end %>
</table>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @songs %>

app/views/songs/index.html.erb
<h1>TuneCore Album Index</h1>
<h4>Search by title, artist, and album.</h4>
<br><br>
<%= form_tag songs_path, :method => 'get', :id => "songs_search" do %>
  <p>
    <%= text_field_tag :title, params[:title], placeholder: "Song Title" %>
    <%= text_field_tag :artist, params[:artist], placeholder: "Artist" %>
    <%= text_field_tag :album, params[:album], placeholder: "Album" %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  </p>
  <br><br>
  <div id="songs"><%= render 'songs' %></div>
<% end %>

app/views/songs/index.js.erb
$("#songs").html("<%= escape_javascript(render("songs")) %>");